import { OfflineContent, SearchOptions, OfflineSearchResult } from './types.js';
import { logger } from '../utils/logger.js';
import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Advanced search indexing for offline content
 */
export class OfflineSearchIndex {
  private readonly indexDir: string;
  private termIndex: Map<string, Map<string, number>> = new Map(); // term -> (docId -> frequency)
  private documentIndex: Map<string, DocumentInfo> = new Map(); // docId -> document info
  private inverseDocumentFrequency: Map<string, number> = new Map(); // term -> IDF score
  private initialized = false;

  constructor(indexDir: string) {
    this.indexDir = indexDir;
  }

  async initialize(): Promise<void> {
    try {
      await fs.mkdir(this.indexDir, { recursive: true });
      await this.loadIndex();
      this.initialized = true;
      logger.info('OfflineSearchIndex initialized');
    } catch (error) {
      logger.error('Failed to initialize OfflineSearchIndex:', error);
      throw error;
    }
  }

  /**
   * Index a document for search
   */
  async indexDocument(content: OfflineContent): Promise<void> {
    this.ensureInitialized();
    
    const docId = content.id;
    const text = `${content.title} ${content.content}`;
    const terms = this.extractTerms(text);
    const termFrequencies = this.calculateTermFrequencies(terms);
    
    // Store document info
    this.documentIndex.set(docId, {
      id: docId,
      title: content.title,
      length: terms.length,
      wikiSource: content.metadata.wikiSource,
      contentType: content.contentType,
      tags: content.metadata.tags || []
    });

    // Update term index
    for (const [term, frequency] of termFrequencies.entries()) {
      if (!this.termIndex.has(term)) {
        this.termIndex.set(term, new Map());
      }
      this.termIndex.get(term)!.set(docId, frequency);
    }

    // Recalculate IDF scores
    this.calculateInverseDocumentFrequencies();
    
    logger.debug(`Indexed document: ${content.title} (${terms.length} terms)`);
  }

  /**
   * Remove a document from the index
   */
  async removeDocument(docId: string): Promise<void> {
    this.ensureInitialized();
    
    // Remove from document index
    this.documentIndex.delete(docId);
    
    // Remove from term index
    for (const [term, docFrequencies] of this.termIndex.entries()) {
      docFrequencies.delete(docId);
      if (docFrequencies.size === 0) {
        this.termIndex.delete(term);
      }
    }
    
    // Recalculate IDF scores
    this.calculateInverseDocumentFrequencies();
    
    logger.debug(`Removed document from index: ${docId}`);
  }

  /**
   * Search the index using TF-IDF scoring
   */
  search(query: string, options: Partial<SearchOptions> = {}): OfflineSearchResult[] {
    this.ensureInitialized();
    
    const {
      limit = 50,
      offset = 0,
      wikiSource,
      contentType,
      tags,
      fuzzyTolerance = 0.0
    } = options;

    const queryTerms = this.extractTerms(query);
    if (queryTerms.length === 0) {
      return [];
    }

    // Calculate scores for all documents
    const scores = new Map<string, number>();
    
    for (const [docId, docInfo] of this.documentIndex.entries()) {
      // Apply filters
      if (wikiSource && docInfo.wikiSource !== wikiSource) continue;
      if (contentType && docInfo.contentType !== contentType) continue;
      if (tags && !tags.some(tag => docInfo.tags.includes(tag))) continue;

      const score = this.calculateTfIdfScore(queryTerms, docId, fuzzyTolerance);
      if (score > 0) {
        scores.set(docId, score);
      }
    }

    // Sort by score and apply pagination
    const sortedResults = Array.from(scores.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(offset, offset + limit);

    // Convert to search results (without actual content - that should be fetched separately)
    return sortedResults.map(([docId, score]) => {
      const docInfo = this.documentIndex.get(docId)!;
      return {
        content: {
          id: docId,
          sourceUrl: '', // To be filled by the caller
          title: docInfo.title,
          content: '', // To be filled by the caller
          contentType: docInfo.contentType,
          lastFetched: new Date(),
          metadata: {
            size: 0,
            wikiSource: docInfo.wikiSource,
            path: '',
            tags: docInfo.tags
          }
        },
        score,
        highlights: [] // To be generated by the caller with full content
      };
    });
  }

  /**
   * Get search suggestions based on term frequency
   */
  getSuggestions(partialQuery: string, limit = 10): string[] {
    this.ensureInitialized();
    
    const partial = partialQuery.toLowerCase().trim();
    if (partial.length < 2) {
      return [];
    }

    const suggestions: Array<{ term: string; frequency: number }> = [];
    
    for (const [term, docFreqs] of this.termIndex.entries()) {
      if (term.startsWith(partial)) {
        const totalFrequency = Array.from(docFreqs.values()).reduce((sum, freq) => sum + freq, 0);
        suggestions.push({ term, frequency: totalFrequency });
      }
    }

    return suggestions
      .sort((a, b) => b.frequency - a.frequency)
      .slice(0, limit)
      .map(s => s.term);
  }

  /**
   * Get index statistics
   */
  getStats(): IndexStats {
    return {
      totalDocuments: this.documentIndex.size,
      totalTerms: this.termIndex.size,
      averageDocumentLength: this.calculateAverageDocumentLength()
    };
  }

  /**
   * Save index to disk
   */
  async saveIndex(): Promise<void> {
    this.ensureInitialized();
    
    try {
      const indexData = {
        termIndex: this.serializeTermIndex(),
        documentIndex: Array.from(this.documentIndex.entries()),
        inverseDocumentFrequency: Array.from(this.inverseDocumentFrequency.entries()),
        version: '1.0'
      };

      const indexFile = path.join(this.indexDir, 'search-index.json');
      await fs.writeFile(indexFile, JSON.stringify(indexData, null, 2));
      
      logger.debug('Search index saved to disk');
    } catch (error) {
      logger.error('Failed to save search index:', error);
    }
  }

  /**
   * Load index from disk
   */
  async loadIndex(): Promise<void> {
    try {
      const indexFile = path.join(this.indexDir, 'search-index.json');
      const indexData = JSON.parse(await fs.readFile(indexFile, 'utf-8'));
      
      this.termIndex = this.deserializeTermIndex(indexData.termIndex);
      this.documentIndex = new Map(indexData.documentIndex);
      this.inverseDocumentFrequency = new Map(indexData.inverseDocumentFrequency);
      
      logger.debug(`Loaded search index: ${this.documentIndex.size} documents, ${this.termIndex.size} terms`);
    } catch (error) {
      // Index doesn't exist or is corrupted, start fresh
      logger.debug('No existing search index found, starting fresh');
      this.termIndex.clear();
      this.documentIndex.clear();
      this.inverseDocumentFrequency.clear();
    }
  }

  async close(): Promise<void> {
    await this.saveIndex();
    this.termIndex.clear();
    this.documentIndex.clear();
    this.inverseDocumentFrequency.clear();
    this.initialized = false;
  }

  // Private helper methods

  private ensureInitialized(): void {
    if (!this.initialized) {
      throw new Error('OfflineSearchIndex not initialized');
    }
  }

  private extractTerms(text: string): string[] {
    return text
      .toLowerCase()
      .replace(/[^\w\s]/g, ' ')
      .split(/\s+/)
      .filter(term => term.length > 2 && !this.isStopWord(term));
  }

  private isStopWord(word: string): boolean {
    const stopWords = new Set([
      'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by',
      'from', 'up', 'about', 'into', 'through', 'during', 'before', 'after', 'above',
      'below', 'between', 'among', 'this', 'that', 'these', 'those', 'his', 'her',
      'its', 'our', 'their', 'what', 'which', 'who', 'when', 'where', 'why', 'how',
      'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such',
      'only', 'own', 'same', 'than', 'too', 'very', 'can', 'will', 'just', 'should'
    ]);
    return stopWords.has(word);
  }

  private calculateTermFrequencies(terms: string[]): Map<string, number> {
    const frequencies = new Map<string, number>();
    
    for (const term of terms) {
      frequencies.set(term, (frequencies.get(term) || 0) + 1);
    }

    // Normalize by document length
    const maxFreq = Math.max(...frequencies.values());
    for (const [term, freq] of frequencies.entries()) {
      frequencies.set(term, freq / maxFreq);
    }

    return frequencies;
  }

  private calculateInverseDocumentFrequencies(): void {
    const totalDocuments = this.documentIndex.size;
    
    for (const [term, docFreqs] of this.termIndex.entries()) {
      const documentsContainingTerm = docFreqs.size;
      const idf = Math.log(totalDocuments / documentsContainingTerm);
      this.inverseDocumentFrequency.set(term, idf);
    }
  }

  private calculateTfIdfScore(queryTerms: string[], docId: string, fuzzyTolerance: number): number {
    let score = 0;
    
    for (const queryTerm of queryTerms) {
      // Exact match
      const termFreqs = this.termIndex.get(queryTerm);
      if (termFreqs && termFreqs.has(docId)) {
        const tf = termFreqs.get(docId)!;
        const idf = this.inverseDocumentFrequency.get(queryTerm) || 0;
        score += tf * idf;
      }
      
      // Fuzzy matching if enabled
      if (fuzzyTolerance > 0) {
        for (const [indexTerm, docFreqs] of this.termIndex.entries()) {
          if (indexTerm !== queryTerm && this.areTermsSimilar(queryTerm, indexTerm, fuzzyTolerance)) {
            if (docFreqs.has(docId)) {
              const tf = docFreqs.get(docId)!;
              const idf = this.inverseDocumentFrequency.get(indexTerm) || 0;
              score += (tf * idf) * 0.5; // Reduce score for fuzzy matches
            }
          }
        }
      }
    }

    // Boost score for title matches
    const docInfo = this.documentIndex.get(docId);
    if (docInfo) {
      const titleTerms = this.extractTerms(docInfo.title);
      for (const queryTerm of queryTerms) {
        if (titleTerms.includes(queryTerm)) {
          score *= 1.5; // 50% boost for title matches
        }
      }
    }

    return score;
  }

  private areTermsSimilar(term1: string, term2: string, threshold: number): boolean {
    if (term1 === term2) return true;
    if (Math.abs(term1.length - term2.length) > 2) return false;
    
    const distance = this.levenshteinDistance(term1, term2);
    const maxLength = Math.max(term1.length, term2.length);
    const similarity = 1 - (distance / maxLength);
    
    return similarity >= threshold;
  }

  private levenshteinDistance(str1: string, str2: string): number {
    const matrix = Array(str2.length + 1).fill(null).map(() => Array(str1.length + 1).fill(null));
    
    for (let i = 0; i <= str1.length; i++) {
      matrix[0][i] = i;
    }
    
    for (let j = 0; j <= str2.length; j++) {
      matrix[j][0] = j;
    }
    
    for (let j = 1; j <= str2.length; j++) {
      for (let i = 1; i <= str1.length; i++) {
        const indicator = str1[i - 1] === str2[j - 1] ? 0 : 1;
        matrix[j][i] = Math.min(
          matrix[j][i - 1] + 1,
          matrix[j - 1][i] + 1,
          matrix[j - 1][i - 1] + indicator
        );
      }
    }
    
    return matrix[str2.length][str1.length];
  }

  private calculateAverageDocumentLength(): number {
    if (this.documentIndex.size === 0) return 0;
    
    const totalLength = Array.from(this.documentIndex.values())
      .reduce((sum, doc) => sum + doc.length, 0);
    
    return totalLength / this.documentIndex.size;
  }

  private serializeTermIndex(): any {
    const serialized: any = {};
    for (const [term, docFreqs] of this.termIndex.entries()) {
      serialized[term] = Array.from(docFreqs.entries());
    }
    return serialized;
  }

  private deserializeTermIndex(serialized: any): Map<string, Map<string, number>> {
    const termIndex = new Map<string, Map<string, number>>();
    for (const [term, docFreqsArray] of Object.entries(serialized)) {
      const docFreqs = new Map<string, number>(docFreqsArray as [string, number][]);
      termIndex.set(term, docFreqs);
    }
    return termIndex;
  }
}

interface DocumentInfo {
  id: string;
  title: string;
  length: number;
  wikiSource: string;
  contentType: string;
  tags: string[];
}

interface IndexStats {
  totalDocuments: number;
  totalTerms: number;
  averageDocumentLength: number;
}
